### PR TITLE
Add pivot feature. #146

### PR DESCRIPTION
**Pull request by epost**
This takes the pivot feature from [ryan4](https://github.com/statebox/cql/tree/ryan4) branch (PR #128) and resolves merge conflicts and other issues as needed.

### CODE REVIEW

**Comment by epost** [comment]
Hi @wisnesky, could you sign off your contribution on this PR using the `clahub` [details](https://www.clahub.com/agreements/statebox/cql) link? When that's done, we can merge this. Thanks!

**Comment by wisnesky** [comment]
Did something change?  Why are these pivot contributions triggering a new (re?) licensing request but not any other the other contributions?

**Comment by epost** [comment]
@wisnesky Hmm, I'm not sure; had you signed off before? Maybe it's because this is a new PR rebased on master?

**Comment by wisnesky** [comment]
Yeah, I signed a PDF over a year ago, not anything online.

**Comment by epost** [comment]
@wisnesky Oh! Right, that's the reason then; [clahub](https://www.clahub.com/agreements/statebox/cql) is an automated service that checks whether every contributor has agreed to the CLA.

**Comment by epost** [comment]
So @wisnesky, would you mind signing off [here](https://www.clahub.com/agreements/statebox/cql) so that this PR can be merged? CLA Hub is preventing the merge from happening, probably because it doesn't know about the PDF. (This should be a one-time thing only, if I'm not mistaken.)

**Comment by wisnesky** [comment]
OK, but for the record I interpret this to mean the original agreement is still in place, and this is a technical fix.

**Comment by epost** [comment]
Thanks @wisnesky! 👍 That is my understanding too. @wires, could you chime in?

**Comment by wires** [comment]
👍 yeah thats correct Ryan, it is not possible with that app to pre-auth people, so everyone has to sign it again. I tried to keep the CLA minimal as a workaround, instead of copying all the legal stuff from the contract verbatim

**Pull request merged**
